title: Feedbacks
modelClass: Omc\Publisher\Models\Feedback
list: $/omc/publisher/models/feedback/columns.yaml
recordUrl: 'omc/publisher/feedbacks/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
