list: $/omc/publisher/models/content/columns.yaml
modelClass: Omc\Publisher\Models\Content
title: Contents
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'omc/publisher/contents/preview/:id'
